acceptance:
  m1_budgets:
  - 10
  - 20
  - 40
  m1_check_diminishing: true
  m1_check_monotonic: true
  m1_grid_size: 1600
  m2_confidence_level: 0.95
  m2_min_improvement_vs_random: 0.15
  m3_max_suboptimality: 1.58
  m3_small_instance_k: 8
  m3_small_instance_n: 200
  m4_coverage_tolerance: 0.05
  m4_morans_alpha: 0.05
  m4_msse_tolerance: 0.2
cv:
  block_strategy: kmeans
  buffer_width_multiplier: 1.5
  ensure_connected: true
  k_folds: 5
  scheme: spatial_block
decision:
  L_FN_gbp: 40000.0
  L_FP_gbp: 8000.0
  L_TN_gbp: 0.0
  L_TP_gbp: 5000.0
  tau_iri: 2.7
diagnostics:
  calibration:
    compute_coverage: true
    compute_msse: true
  morans_i:
    permutations: 999
    weight_type: adjacency
evi:
  compute_for:
  - greedy_mi
  method: unscented
  monte_carlo_samples: 500
  unscented_alpha: 1.0
  unscented_beta: 2.0
  unscented_kappa: 0.0
experiment:
  name: rdt_sensor_optimization_v1
  output_dir: runs
  seed: 202501
geometry:
  h: 5.0
  mode: grid2d
  nx: 40
  ny: 40
logging:
  console: true
  file: true
  jsonl_metrics: true
  level: INFO
numerics:
  cholesky_nugget: 1.0e-09
  linear_solver_tol: 1.0e-08
  logdet_method: cholesky
  pcg_max_iter: 1000
plots:
  budget_curves:
    metrics:
    - expected_loss
    - rmse
    - mae
    show_ci: true
  critical_difference:
    alpha: 0.05
    test: nemenyi
  dpi: 300
  performance_profile:
    tau_max: 3.0
  save_formats:
  - png
  - pdf
  style: seaborn-v0_8-paper
prior:
  alpha: 2
  beta: 1.0e-06
  kappa: 0.08
  mu_prior_mean: 1.5
  mu_prior_std: 0.0
  nu: 1.0
  sigma2: 0.04
selection:
  budgets:
  - 5
  - 10
  - 20
  - 40
  - 60
  - 80
  greedy_aopt:
    hutchpp_probes: 20
    lazy: true
    trace_estimator: hutchpp
  greedy_mi:
    cost_normalized: true
    lazy: true
    warmstart_enum: false
  methods:
  - greedy_mi
  - greedy_aopt
  - uniform
  - random
sensors:
  pool_fraction: 0.25
  pool_strategy: grid_subsample
  type_mix:
  - 0.4
  - 0.4
  - 0.2
  types:
  - cost_gbp: 10000.0
    footprint: point
    name: inertial_profiler
    noise_std: 0.1
  - cost_gbp: 5000.0
    footprint: avg3x3
    name: photogrammetry
    noise_std: 0.25
  - cost_gbp: 500.0
    footprint: avg5x5
    name: smartphone
    noise_std: 0.5
uq:
  bootstrap_method: spatial_block
  bootstrap_samples: 1000
  compute_crps: false
  confidence_level: 0.95
  coverage_percentile: 90
